name: bokain_models
description: A collection of models and their services for bokain
version: 0.2.163
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://www.bokain.se

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular: '^4.0.0-beta'
  angular_components: '^0.6.0-beta'
  firebase: '^4.0.0'
  fo_components:
    path: ../../Visurus/FoComponents
  http: '^0.11.3+14'
  vi_auth_client:
    path: ../../Visurus/ViAuthClient
  random_string: ^0.0.1

transformers:
  - angular