name: bokain_models
description: A collection of models for bokain
version: 0.2.43
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://www.bokain.se

environment:
  sdk: '>=1.23.0-dev.11.11 <2.0.0'

dependencies:
  collection: ^1.12.0