name: bokain_models
description: A collection of models for bokain
version: 0.2.26
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://www.bokain.se

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  collection: ^1.12.0