name: bokain_models
description: A collection of models and their services for bokain
version: 0.2.163
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://www.bokain.se

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  angular: '^4.0.0'
  angular_components: '^0.8.0'
  firebase: '^4.0.0'
  fo_components:
    path: ../../Visurus/FoComponents
  http: '^0.11.3+14'
  #sass_builder: ^1.0.1
  vi_auth_client:
    path: ../../Visurus/ViAuthClient

transformers:
- angular