name: bokain_models
description: A collection of models and their services for bokain
version: 0.2.160
author: Patrick Minogue <patrick.minogue@gmail.com>
homepage: https://www.bokain.se

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: '^3.1.0'
  angular_components: '^0.5.2'
  firebase: '^3.0.2'
  fo_components: ^0.0.1389
  http: '^0.11.3+13'

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'