import '../../static_model/skin_type.dart';
import 'package:angular/di.dart';

@Injectable()
class SkinTypeService
{
  SkinType get(String id) => _data.containsKey(id) ? _data[id] : null;

  Map<String, SkinType> get data => _data;

  final Map<String, SkinType> _data =
  {
    "1" : new SkinType("1", "acne",
    [
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : 1,
        "pustules" : "*",
        "cysts" : "*",
        "nodules" : "*",
        "seborrhea" : 0,
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : 2,
        "pustules" : "*",
        "cysts" : "*",
        "nodules" : "*",
        "seborrhea" : 1,
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : 3,
        "pustules" : "*",
        "cysts" : "*",
        "nodules" : "*",
        "seborrhea" : "*",
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : "*",
        "pustules" : 1,
        "cysts" : "*",
        "nodules" : "*",
        "seborrhea" : "*",
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : "*",
        "pustules" : 2,
        "cysts" : "*",
        "nodules" : "*",
        "seborrhea" : "*",
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : "*",
        "pustules" : 3,
        "cysts" : "*",
        "nodules" : "*",
        "seborrhea" : "*",
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : "*",
        "pustules" : "*",
        "cysts" : 1,
        "nodules" : "*",
        "seborrhea" : "*",
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : "*",
        "pustules" : "*",
        "cysts" : 2,
        "nodules" : "*",
        "seborrhea" : "*",
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : "*",
        "pustules" : "*",
        "cysts" : 3,
        "nodules" : "*",
        "seborrhea" : "*",
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : "*",
        "pustules" : "*",
        "cysts" : "*",
        "nodules" : 1,
        "seborrhea" : "*",
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : "*",
        "pustules" : "*",
        "cysts" : "*",
        "nodules" : 2,
        "seborrhea" : "*",
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
      {
        "open_comedones" : "*",
        "closed_comedones" : "*",
        "papules" : "*",
        "pustules" : "*",
        "cysts" : "*",
        "nodules" : 3,
        "seborrhea" : "*",
        "rosacea" : 0,
        "milia" : "*",
        "pigmentation" : "*",
        "surface_blood_vessels" : "*",
        "acne_scars" : "*",
        "texture" : "*"
      },
    ]),
    "2" : new SkinType("2", "combination_skin", []),
    "3" : new SkinType("3", "oily",
        [
          {
            "open_comedones" : 0,
            "closed_comedones" : 0,
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : false,
            "milia" : false,
            "pigmentation" : false,
            "surface_blood_vessels" : false,
            "acne_scars" : false,
            "texture" : "oily"
          }
        ]),
    "4" : new SkinType("4", "milia",
        [
          {
            "open_comedones" : 0,
            "closed_comedones" : 0,
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : false,
            "milia" : true,
            "pigmentation" : false,
            "surface_blood_vessels" : false,
            "acne_scars" : false,
            "texture" : "*"
          }
        ]),
    "5" : new SkinType("6", "pigmentation",
        [
          {
            "open_comedones" : 0,
            "closed_comedones" : 0,
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : false,
            "milia" : false,
            "pigmentation" : true,
            "surface_blood_vessels" : false,
            "acne_scars" : false,
            "texture" : "*"
          }
        ]),
    "7" : new SkinType("7", "comedones",
        [
          {
            "open_comedones" : "*",
            "closed_comedones" : 2,
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 1,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : "*",
            "closed_comedones" : 3,
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 1,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : 2,
            "closed_comedones" : "*",
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 1,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : 3,
            "closed_comedones" : "*",
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 1,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : "*",
            "closed_comedones" : 1,
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : "*",
            "closed_comedones" : 2,
            "papules" : 1,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : "*",
            "closed_comedones" : 3,
            "papules" : 1,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : "*",
            "closed_comedones" : 2,
            "papules" : 1,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 1,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : "*",
            "closed_comedones" : 3,
            "papules" : 1,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 2,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : 1,
            "closed_comedones" : "*",
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : 2,
            "closed_comedones" : "*",
            "papules" : 1,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : 3,
            "closed_comedones" : "*",
            "papules" : 1,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : 2,
            "closed_comedones" : "*",
            "papules" : 1,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 1,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : 3,
            "closed_comedones" : "*",
            "papules" : 1,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 1,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
          {
            "open_comedones" : 3,
            "closed_comedones" : "*",
            "papules" : 1,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 2,
            "rosacea" : 0,
            "milia" : "*",
            "pigmentation" : "*",
            "surface_blood_vessels" : "*",
            "acne_scars" : "*",
            "texture" : "*"
          },
        ]),
    "8" : new SkinType("8", "rosacea",
        [
          {
            "open_comedones" : "*",
            "closed_comedones" : "*",
            "papules" : "*",
            "pustules" : "*",
            "cysts" : "*",
            "nodules" : "*",
            "seborrhea" : "*",
            "rosacea" : true,
            "milia" : false,
            "pigmentation" : false,
            "surface_blood_vessels" : false,
            "acne_scars" : false,
            "texture" : "*"
          },
        ]),
    "9" : new SkinType("9", "seborrhea", []),
    "10" : new SkinType("10", "dry",
        [
          {
            "open_comedones" : 0,
            "closed_comedones" : 0,
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : false,
            "milia" : false,
            "pigmentation" : false,
            "surface_blood_vessels" : false,
            "acne_scars" : false,
            "texture" : "dry"
          }
        ]),
    "11" : new SkinType("11", "surface_blood_vessels",
        [
          {
            "open_comedones" : 0,
            "closed_comedones" : 0,
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : false,
            "milia" : false,
            "pigmentation" : false,
            "surface_blood_vessels" : true,
            "acne_scars" : false,
            "texture" : "*"
          }
        ]),
    "12" : new SkinType("12", "acne_scars",
        [
          {
            "open_comedones" : 0,
            "closed_comedones" : 0,
            "papules" : 0,
            "pustules" : 0,
            "cysts" : 0,
            "nodules" : 0,
            "seborrhea" : 0,
            "rosacea" : false,
            "milia" : false,
            "pigmentation" : false,
            "surface_blood_vessels" : false,
            "acne_scars" : true,
            "texture" : "*"
          }
        ])
  };
}