class Phrases
{
  static final Map<String, Map<String, String>> data =
  {
    "sv":
    {
      "1_pronounced" : "1:a",
      "2_prounounced" : "2:a",
      "3_pronounced" : "3:e",
      "4_pronounced" : "4:e",
      "5_pronounced" : "5:e",
      "6_pronounced" : "6:e",
      "7_pronounced" : "7:e",
      "8_pronounced" : "8:e",
      "9_pronounced" : "9:e",
      "10_pronounced" : "10:e",
      "11_pronounced" : "11:e",
      "12_pronounced" : "12:e",
      "13_pronounced" : "13:e",
      "14_pronounced" : "14:e",
      "15_pronounced" : "15:e",
      "16_pronounced" : "16:e",
      "17_pronounced" : "17:e",
      "18_pronounced" : "18:e",
      "19_pronounced" : "19:e",
      "20_pronounced" : "20:e",
      "21_pronounced" : "21:a",
      "22_pronounced" : "22:a",
      "23_pronounced" : "23:e",
      "24_pronounced" : "24:e",
      "25_pronounced" : "25:e",
      "26_pronounced" : "26:e",
      "27_pronounced" : "27:e",
      "28_pronounced" : "28:e",
      "29_pronounced" : "29:e",
      "30_pronounced" : "30:e",
      "31_pronounced" : "31:a",
      "32_pronounced" : "32:a",
      "account" : "konto",
      "active" : "aktiv",
      "add" : "lägg till",
      "after_margin" : "städmarginal",
      "alert" : "varning",
      "anyone" : "vem som helst",
      "article_no" : "artikelnummer",
      "associate" : "anslut",
      "associated" : "ansluten",
      "associateds" : "anslutna",
      "at" : "på",
      "back" : "tillbaka",
      "belongs_to" : "tillhör",
      "benefits" : "fördelar",
      "book" : "boka in",
      "bookables" : "bokningsbara",
      "booking" : "bokning",
      "booking_cancel" : "avboka",
      "booking_cancel_code" : "avbokningskod",
      "booking_cancel_code_not_found" : "kunde inte hitta någon bokning med den angivna avbokningskoden.",
      "booking_cancel_description" : "Ange koden du fick i din bokningsbekräftelse för att avboka din behandling. Vänligen observera att avbokningen måste göras minst %cancel_booking_hours% timmar innan behandlingstillfället.",
      "booking_cancellation" : "avbokning",
      "booking_cancellation_confirmation" : "avbokningsbekräftelse",
      "booking_cancellation_terms" : "Avbokningspolicy: Vid uteblivet besök debiteras hela behandlingskostnaden.",
      "booking_cancelled" : "Avbokning genomförd.",
      "booking_confirm" : "bekräfta bokning",
      "booking_confirm_text" :  "kontrollera att uppgifterna ovan stämmer innan du slutför bokningen",
      "booking_confirmation" : "bokningsbekräftelse",
      "booking_confirmation_send" : "skicka bokningsbekräftelse till kunden",
      "booking_details" : "bokningsinformation",
      "booking_history" : "bokningshistorik",
      "bookings" : "bokningar",
      "booking_rank" : "bokningsranking",
      "booking_terms" : "Avbokning skall lämnas senast 24 tim innan avtalad tid. Vid utebliven behandling sker debitering. Gäller även vid sjukdom samma dag.",
      "break" : "rast",
      "buy_price_sek" : "inköpspris",
      "calendar" : "kalender",
      "calendar_mode" : "kalenderläge",
      "cancel" : "avbryt",
      "careof" : "C/O",
      "categories" : "kategorier",
      "category" : "kategori",
      "choose" : "välj",
      "city" : "stad",
      "close" : "stäng",
      "color" : "färg",
      "content" : "innehåll",
      "comments" : "kommentarer",
      "comments_external" : "externa kommentarer",
      "comments_internal" : "interna kommentarer",
      "company" : "företag",
      "complete_booking" : "slutför bokning",
      "confirm" : "bekräfta",
      "confirm_autofill" : "bekräfta autofyll",
      "confirm_autofill_text" : "Det finns redan en kund registrerad med dessa uppgifter, vill du använda detta konto?",
      "confirm_cancel_booking" : "Är du säker på att du vill avboka denna tid?",
      "confirm_set_all_day_sick" : "Är du säker på att du vill sjukanmäla användaren denna dag?",
      "confirm_set_all_day_sick_info" : "Eventuella tider kommer automatiskt att avbokas, och operationen går ej att ångra.",
      "confirm_remove" : "bekräfta borttagning av objekt",
      "confirm_save" : "du har osparade ändringar, tryck OK för att spara eller AVBRYT för att ignorera ändringarna",
      "contact" : "kontakt",
      "could_not_cancel_booking" : "avbokningen kunde inte genomföras",
      "country" : "land",
      "country_gb" : "storbritannien",
      "country_se" : "sverige",
      "currency" : "kr",
      "customer" : "kund",
      "customers" : "kunder",
      "customer_details" : "kunduppgifter",
      "customer_with_this_email_already_exists" : "Det finns redan en kund med denna e-post",
      "customer_with_this_phone_already_exists" : "Det finns redan en kund med detta telefonnummer",
      "customer_with_this_social_number_already_exists" : "Det finns redan en kund med detta personnummer",
      "dashboard" : "dashboard",
      "day" : "dag",
      "delete" : "ta bort",
      "delete_are_you_sure" : "Är du säker på att du vill ta bort %model%? Operationen går inte att ångra.",
      "description" : "beskrivning",
      "description_long" : "Lång beskrivning",
      "description_short" : "Kort beskrivning",
      "details" : "uppgifter",
      "disabled" : "inaktiverad",
      "discount_code" : "rabattkod",
      "duration" : "varaktighet",
      "duration_minutes" : "varaktighet (minuter)",
      "dynamic_time" : "dynamisk tid",
      "edit" : "redigera",
      "effects" : "effekter",
      "email" : "e-post",
      "email_pronounced" : "denna e-post",
      "email_cancel_booking" : '<table width="550" cellpadding="0" cellspacing="0" style="width:550px; border:1px solid #eeeeee; font-family: Arial, Helvetica Neue, Helvetica, sans-serif; display: block; margin:30px auto;"><tr style="text-align: center;"><td><h4 style="margin-top:0; margin-bottom:0; padding-top:15px; width:550px; padding-bottom:15px; background-color:#01a79d; color:#ffffff;">Avbokningsbekräftelse</h4></td></tr><tr><td><table width="550" cellspacing="15" style="border:0"><tr><td>Hej %customer_firstname%!</td></tr><tr><td>Följande bokning har nu avbokats:</td></tr><tr><td><table width="520" cellspacing="0" cellpadding="0" style="border:0"><tr><td><strong>Tjänst:</strong></td><td>%service_name%</td></tr><tr><td><strong>Tid:</strong></td><td>%date% kl. %start_time% - %end_time%</td></tr><tr><td><strong>Plats:</strong></td><td>%salon_name%, %salon_address%</td></tr><tr><td><strong>Telefon:</strong></td><td>%salon_phone%</td></tr></table></td></tr><tr><td> Med vänliga hälsningar<br /> %user_name%</td></tr></table></td></tr></table>',
      "email_cancel_booking_sick" : '<table width="550" cellpadding="0" cellspacing="0" style="width:550px; border:1px solid #eeeeee; font-family: Arial, Helvetica Neue, Helvetica, sans-serif; display: block; margin:30px auto;"><tr style="text-align: center;"><td><h4 style="margin-top:0; margin-bottom:0; padding-top:15px; width:550px; padding-bottom:15px; background-color:#01a79d; color:#ffffff;">Din tid har blivit avbokad pga. sjukdom</h4></td></tr><tr><td><table width="550" cellspacing="15" style="border:0"><tr><td>Hej %customer_firstname%!</td></tr><tr><td>Nedanstående tid har tyvärr blivit inställd på grund av att utövaren är sjukfrånvarande. Vi ber om ursäkt för det inträffade och välkomnar dig att boka en ny tid.</td></tr><tr><td><table width="520" cellspacing="0" cellpadding="0" style="border:0"><tr><td><strong>Tjänst:</strong></td><td>%service_name%</td></tr><tr><td><strong>Tid:</strong></td><td>%date% kl. %start_time% - %end_time%</td></tr><tr><td><strong>Plats:</strong></td><td>%salon_name%, %salon_address%</td></tr><tr><td><strong>Telefon:</strong></td><td>%salon_phone%</td></tr></table></td></tr><tr><td> Med vänliga hälsningar<br /> %user_name%</td></tr></table></td></tr></table>',
      "email_new_booking" : '<table width="550" cellpadding="0" cellspacing="0" style="width:550px; border:1px solid #eeeeee; font-family: Arial, Helvetica Neue, Helvetica, sans-serif; display: block; margin:30px auto;"><tr style="text-align: center;"><td><h4 style="margin-top:0; margin-bottom:0; padding-top:15px; width:550px; padding-bottom:15px; background-color:#01a79d; color:#ffffff;">Bokningsbekräftelse</h4></td></tr><tr><td><table width="550" cellspacing="15" style="border:0"><tr><td>Tack för din bokning!</td></tr><tr><td>Du har bokat följande:</td></tr><tr><td><table width="520" cellspacing="0" cellpadding="0" style="border:0"><tr><td><strong>Tjänst:</strong></td><td>%service_name%</td></tr><tr><td><strong>Tid:</strong></td><td>%date% kl. %start_time% - %end_time%</td></tr><tr><td><strong>Plats:</strong></td><td>%salon_name%, %salon_address%</td></tr><tr><td><strong>Telefon:</strong></td><td>%salon_phone%</td></tr></table></td></tr><tr><td> <strong>Avbokningsregler:</strong><br /> Din bokning kan avbokas senast %latest_cancel_booking_time%<br /> Avboka på: <a href="https://www.bokain.se/cancel">https://www.bokain.se/cancel</a><br /> Din avbokningskod är %cancel_code%</td></tr><tr><td> Med vänliga hälsningar<br /> %user_name%</td></tr></table></td></tr></table>',
      "email_reschedule_booking" : '<table width="550" cellpadding="0" cellspacing="0" style="width:550px; border:1px solid #eeeeee; font-family: Arial, Helvetica Neue, Helvetica, sans-serif; display: block; margin:30px auto;"><tr style="text-align: center;"><td><h4 style="margin-top:0; margin-bottom:0; padding-top:15px; width:550px; padding-bottom:15px; background-color:#01a79d; color:#ffffff;">Din tid har blivit ombokad</h4></td></tr><tr><td><table width="550" cellspacing="15" style="border:0"><tr><td>Hej %customer_firstname%!</td></tr><tr><td>Din tid har blivit ombokad enligt nedan:</td></tr><tr><td><table width="520" cellspacing="0" cellpadding="0" style="border:0"><tr><td><strong>Tjänst:</strong></td><td>%service_name%</td></tr><tr><td><strong>Tid:</strong></td><td>%date% kl. %start_time% - %end_time%</td></tr><tr><td><strong>Plats:</strong></td><td>%salon_name%, %salon_address%</td></tr><tr><td><strong>Telefon:</strong></td><td>%salon_phone%</td></tr></table></td></tr><tr><td> <strong>Avbokningsregler:</strong><br /> Din bokning kan avbokas senast %latest_cancel_booking_time%<br /> Avboka på: <a href="https://www.bokain.se/cancel">https://www.bokain.se/cancel</a><br /> Din avbokningskod är %cancel_code%</td></tr><tr><td> Med vänliga hälsningar<br /> %user_name%</td></tr></table></td></tr></table>',
      "employee" : "utövare",
      "enter_a_cancel_code" : "Ange en avbokningskod",
      "enter_a_city" : "Ange en stad",
      "enter_a_firstname" : "Ange ett förnamn",
      "enter_integers_only" : "Ange ett heltal",
      "enter_a_lastname" : "Ange ett efternamn",
      "enter_a_name" : "Ange ett namn",
      "enter_no_spaces" : "Detta fält får inte innehålla mellanslag",
      "enter_a_phone" : "Ange ett telefonnummer",
      "enter_a_postal_code" : "Ange ett postnummer",
      "enter_a_search_rank" : "Ange en sökranking",
      "enter_a_social_number" : "Ange ett personnummer",
      "enter_a_street" : "Ange en gatuaddress",
      "enter_a_url_name" : "Ange ett URL-namn",
      "enter_a_value" : "Ange ett värde",
      "enter_an_article_no" : "Ange ett artikelnummer",
      "enter_alphabet_characters_only" : "enbart bokstäver är tillåtna i detta fält",
      "enter_alpha_numeric_values_only" : "enbart bokstäver och siffror är tillåtna i detta fält",
      "enter_an_email" : "Ange en e-post",
      "enter_numbers_only" : "enbart siffror är tillåtna i detta fält",
      "enter_valid_phone" : "Ange ett giltigt telefonnummer (+46)8 123 456",
      "enter_valid_swedish_cellphone_without_spaces" : "Ange ett giltigt mobilnummer utan mellanslag (0712345678)",
      "enter_valid_swedish_ssn" : "Ange ett giltigt svenskt personnummer utan mellanslag eller bindestreck (YYYYMMDDXXXX)",
      "enter_valid_cancel_booking_code" : "Ange en giltig bokningskod (ABC123)",
      "numeric_max_exceeded" : "värdet får inte överstiga %max%",
      "numeric_min_exceeded" : "värdet får inte understiga %min%",
      "entries" : "inlägg",
      "error_occurred" : "ett fel inträffade",
      "false" : "falskt",
      "finish" : "slutför",
      "friday" : "fredag",
      "grade" : "gradering",
      "i_accept_the_terms" : "jag accepterar villkoren",
      "in_minutes" : "(minuter)",
      "index.html" : "Dashboard",
      "information" : "information",
      "firstname" : "förnamn",
      "frozen" : "fryst",
      "function" : "funktion",
      "hello" : "hej",
      "image" : "bild",
      "image_must_be_set" : "Ange en bild",
      "ingredient" : "ingrediens",
      "ingredients" : "ingredienser",
      "invalid_url" : "felaktig URL",
      "invoice_sent" : "faktura skickad",
      "language" : "språk",
      "language_en" : "engelska",
      "language_sv" : "svenska",
      "lastname" : "efternamn",
      "latest_cancel_booking_time_overdue" : "Tidsfristen för avbokning har passerats för denna bokning.",
      "location" : "plats",
      "log" : "logg",
      "log_user_logged_in" : "%user% har loggat in",
      "log_user_recommended_products" : "%user% har rekommenderat produkter: %products% till kund: %customer%",
      "log_user_recommended_service" : "%user% har rekommenderat behandling: %service% till kund: %customer% på %salon%",
      "log_user_received_chat_message" : "%user% har fått ett chattmeddelande från kund: %customer%",
      "log_user_sent_chat_message" : "%user% har skickat ett chattmeddelande till kund: %customer%",
      "log_user_auto_assigned_consultation" : "%user% har blivit tilldelad online hudkonsultation, kund: %customer%",
      "log_user_journal_entry" : "%user% har lagt till ett inlägg i kundjournal, kund: %customer%",
      "log_user_marked_noshow" : "%user% har markerat no-show på kund: %customer%",
      "log_user_edited_schedule" : "%user% har redigerat schema, markeringsläge: %state%, datum: %date% på %salon%",
      "log_user_cancelled_booking" : "%user% har avbokat behandling: %service% på kund %customer%",
      "login" : "logga in",
      "logo" : "logotyp",
      "logo_as" : "logotyp (AS)",
      "logo_ssc" : "logotyp (SSC)",
      "menu" : "meny",
      "meta_description" : "META-beskrivning",
      "meta_keywords" : "META-nyckelord",
      "monday" : "måndag",
      "month" : "månad",
      "month_1" : "januari",
      "month_2" : "februari",
      "month_3" : "mars",
      "month_4" : "april",
      "month_5" : "maj",
      "month_6" : "juni",
      "month_7" : "juli",
      "month_8" : "augusti",
      "month_9" : "september",
      "month_10" : "oktober",
      "month_11" : "november",
      "month_12" : "december",
      "name" : "namn",
      "name_pronounced" : "detta namn",
      "new" : "ny",
      "new_booking" : "ny bokning",
      "new_customer" : "ny kund",
      "new_entry" : "nytt inlägg",
      "new_ingredient" : "ny ingrediens",
      "new_product" : "ny produkt",
      "new_product_category" : "ny produktkategori",
      "new_room" : "nytt rum",
      "new_salon" : "ny salong",
      "new_service" : "ny tjänst",
      "new_service_addon" : "ny tilläggstjänst",
      "new_user" : "ny användare",
      "next" : "nästa",
      "no" : "nej",
      "no_available_times" : "inga lediga tider",
      "no_results" : "inga resultat",
      "no_services_available" : "Inga tillgängliga tjänster",
      "none" : "inget",
      "not" : "ej",
      "not_selected" : "ej vald",
      "only" : "enbart",
      "open" : "öppen",
      "order_history" : "orderhistorik",
      "origin" : "ursprung",
      "other" : "övrigt",
      "page" : "sida",
      "password" : "lösenord",
      "pcs" : "st",
      "phone" : "telefon",
      "picture" : "bild",
      "pictures" : "bilder",
      "please_note_spam_email" : "Var god notera att bekräftelsen kan hamna i skräpkorgen. Avbokning måste ske minst 24 timmar innan behandlingstillfället. Gäller äv vid sjukdom samma dag.",
      "postal_code" : "postnummer",
      "practician" : "utövare",
      "previous" : "föregående",
      "price" : "pris",
      "price_sek" : "pris (kr)",
      "product" : "produkt",
      "product_bundle" : "produktpaket",
      "product_bundles" : "produktpaket",
      "product_category" : "produktkategori",
      "product_categories" : "produktkategorier",
      "product_routine" : "behandlingsrutin",
      "product_routines" : "behandlingsrutiner",
      "product_type" : "produkttyp",
      "product_with_this_article_no_already_exists" : "Det finns redan en produkt med detta artikelnummer",
      "product_with_this_name_already_exists" : "Det finns redan en produkt med detta namn",
      "product_with_this_url_name_already_exists" : "Det finns redan en produkt med detta URL-namn",
      "products" : "produkter",
      "profile_image" : "profilbild",
      "properties" : "egenskaper",
      "rebook" : "omboka",
      "rebooking" : "ombokning",
      "related_products" : "relaterade produkter",
      "required_field_missing" : "Obligatoriskt värde saknas",
      "reset" : "nollställ",
      "room" : "rum",
      "rooms" : "rum",
      "room_pronounced" : "detta rum",
      "rows" : "rader",
      "salon" : "salong",
      "salon_details" : "salongens uppgifter",
      "salons" : "salonger",
      "salon_with_this_name_already_exists" : "Det finns redan en salong med detta namn",
      "saturday" : "lördag",
      "save" : "spara",
      "schedule" : "schema",
      "schedule_mode" : "schemaläge",
      "score" : "poäng",
      "search" : "sök",
      "search_rank" : "sökranking",
      "select" : "välj",
      "selected" : "vald",
      "selecteds" : "valda",
      "selection_state" : "markeringsläge",
      "send_email_notification" : "skicka e-post notifikation",
      "send_invoice" : "skicka faktura",
      "service" : "tjänst",
      "service_addon" : "tilläggstjänst",
      "service_addon_details" : "tillägstjänstens uppgifter",
      "service_addon_not_selected" : "tilläggstjänst ej vald",
      "service_addons" : "tilläggstjänster",
      "service_addon_with_this_name_already_exists" : "Det finns redan en tilläggstjänst med detta namn",
      "service_details" : "tjänstens uppgifter",
      "services" : "tjänster",
      "settings" : "inställningar",
      "sick" : "sjuk",
      "side_effects" : "biverkningar",
      "skin_consultation" : "hudkonsultation",
      "skin_type" : "hudtyp",
      "skin_type_acne" : "akne",
      "skin_type_aging" : "åldrande",
      "skin_type_combination_skin" : "blandhy",
      "skin_type_oily" : "fet hy",
      "skin_type_sensitive" : "känslig hy",
      "skin_type_milia" : "milier",
      "skin_type_normal" : "normal hy",
      "skin_type_pigmentation" : "pigmentfläckar",
      "skin_type_comedones" : "pormaskar",
      "skin_type_rosacea" : "rosacea",
      "skin_type_seborrhea" : "seborré",
      "skin_type_sun_damaged" : "solskadad hy",
      "skin_type_dry" : "torr hy",
      "social_number" : "personnummer",
      "social_number_pronounced" : "detta personnummer",
      "ssn_error_could_not_fetch" : "kunde inte hämta uppgifter med detta personnummer",
      "ssn_fetch" : "hämta personuppgifter",
      "start_time" : "starttid",
      "stock" : "lager",
      "street" : "gatuadress",
      "sub_product" : "subprodukt",
      "sub_products" : "subprodukter",
      "sunday" : "söndag",
      "terms" : "allmänna villkor",
      "thank_you" : "tack",
      "thank_you_for_booking" : "tack för din bokning!",
      "thursday" : "torsdag",
      "time" : "tid",
      "time_already_booked" : "Denna tid är inte längre tillgänglig",
      "times" : "tider",
      "true" : "sant",
      "try_again" : "vänligen försök igen, eller kontakta oss om felet kvarstår.",
      "tuesday" : "tisdag",
      "type" : "typ",
      "undo" : "ångra",
      "url_name" : "URL-namn",
      "url_salon_not_found" : "Kunde inte hitta den salong som angetts i länken.",
      "url_service_incompatible_with_url_salon" : "Tjänsten som angetts i länken utförs inte på salongen som angetts.",
      "url_service_not_found" : "Kunde inte hitta den tjänst som angetts i länken.",
      "usage_instructions" : "användarinstruktioner",
      "user" : "användare",
      "users" : "användare",
      "user_details" : "användaruppgifter",
      "user_with_this_email_already_exists" : "Det finns redan en användare med denna e-post",
      "user_with_this_phone_already_exists" : "Det finns redan en användare med detta telefonnummer",
      "user_with_this_social_number_already_exists" : "Det finns redan en användare med detta personnummer",
      "vat" : "moms",
      "volume" : "volym (ml)",
      "warning" : "varning",
      "we_have_just_registered_your_booking" : "Vi har just registrerat din bokning.",
      "webshop" : "webshop",
      "wednesday" : "onsdag",
      "week" : "vecka",
      "weekday_1_pronounced" : "måndagen den",
      "weekday_2_pronounced" : "tisdagen den",
      "weekday_3_pronounced" : "onsdagen den",
      "weekday_4_pronounced" : "torsdagen den",
      "weekday_5_pronounced" : "fredagen den",
      "weekday_6_pronounced" : "lördagen den",
      "weekday_7_pronounced" : "söndagen den",
      "weight" : "vikt (g)",
      "yes" : "ja",
      "you_will_receive_booking_confirmation_shortly_to" : "Inom kort kommer du att få en bokningsbekräftelse skickad till",
      "your" : "din"
    }
  };
}